// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'button': string;
  'buttonBig': string;
  'buttonCheckbox': string;
  'buttonCheckmark': string;
  'buttonCheckmarkChecked': string;
  'buttonDelete': string;
  'buttonFormClose': string;
  'buttonIcon': string;
  'buttonIconTable': string;
  'buttonListing': string;
  'buttonNotificationClose': string;
  'buttonSectionClose': string;
  'buttonSubmit': string;
  'buttonTable': string;
  'errorLabel': string;
  'flexFiller': string;
  'icon': string;
  'iconButton': string;
  'iconTableButton': string;
  'labelMixin': string;
  'labelled': string;
  'labelledContent': string;
  'labelledLabel': string;
  'lineInput': string;
  'lineInputInput': string;
  'link': string;
  'loader': string;
  'loaderUpload': string;
  'page': string;
  'pageMain': string;
  'textInput': string;
  'workbenchBorderDarkLightMixin': string;
  'workbenchBorderLightDarkMixin': string;
}
export const cssExports: CssExports;
export default cssExports;
