// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'actions': string;
  'actionsElementCenter': string;
  'actionsFullrow': string;
  'actionsSet': string;
  'actionsSetBaseline': string;
  'actionsSetEven': string;
  'actionsSetRight': string;
  'actionsSubmit': string;
}
export const cssExports: CssExports;
export default cssExports;
