// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'pager': string;
  'pagerLeft': string;
  'pagerPage': string;
  'pagerPageSelected': string;
  'pagerRight': string;
}
export const cssExports: CssExports;
export default cssExports;
